###
GET http://localhost:8091/api/v1/employees

{}

###
GET http://localhost:8091/api/v1/employees/1

{}

###
DELETE http://localhost:8091/api/v1/employees/2

{}

###
DELETE http://localhost:8091/api/v1/employees/delete-list
Content-Type: application/json

["2", "3"]

###
POST http://localhost:8091/api/v1/employees
Content-Type: application/json

{
"id": "9",
"firstName": "Тест",
"secondName": "Тестовский",
"patronymic": "Тестович"
}

### Если был задействован метод DELETE выше
POST http://localhost:8091/api/v1/employees
Content-Type: application/json

{
"id": "2",
"firstName": "Петров",
"secondName": "Петр",
"patronymic": "Петрович"
}

###
PUT http://localhost:8091/api/v1/employees/2
Content-Type: application/json

{
"id": "2",
"firstName": "Филимон",
"secondName": "Филимонов",
"patronymic": "Филимонович"
}

### Тестирование edge-cases
### Запрос явно отсутствующего id
GET http://localhost:8091/api/v1/employees/2025

{}
